Add OSRuntimeStatus
edgehog-device-manager/edgehog-astarte-interfaces pull request #3
Opened 2021-11-05 15:45 UTC by FrancescoVaiani

This commits add an interface with the porpoise of expose a `top` like data set , such as uptime and available memory.

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2021-11-05 16:50 UTC, bettio requested changes

2021-11-05 16:50 UTC, bettio commented on io.edgehog.devicemanager.OSRuntimeStatus.json
> +  "interface_name": "io.edgehog.devicemanager.OSRuntimeStatus",
I was thinking about it, and maybe SystemStatus might be a better naming.

2021-11-05 16:51 UTC, bettio requested changes

2021-11-05 16:51 UTC, bettio commented on io.edgehog.devicemanager.OSRuntimeStatus.json
> +    {
let's add a TTL from day 0. I was thinking 60 days as default

2021-11-08 10:11 UTC, bettio requested changes

2021-11-08 10:11 UTC, bettio commented on io.edgehog.devicemanager.OSRuntimeStatus.json
> +      "endpoint": "/systemStatus/bootId",
I think an uuid might be better.

2021-11-08 10:26 UTC, bettio commented on io.edgehog.devicemanager.OSRuntimeStatus.json
> +      "endpoint": "/systemStatus/availMemory",
availMemoryBytes

2021-11-08 10:28 UTC, bettio requested changes

2021-11-08 10:28 UTC, bettio commented on io.edgehog.devicemanager.OSRuntimeStatus.json
> +      "endpoint": "/systemStatus/uptime",
uptimeMillis

2021-11-08 10:28 UTC, bettio commented on io.edgehog.devicemanager.OSRuntimeStatus.json
> +      "description": "Get time in minutes since boot",
I think we might go with milliseconds, since we can get them for free.

2021-11-08 17:09 UTC, bettio requested changes
I would rephrase the commit message: `This commits add an interface with the porpoise of expose a top like data set , such as uptime and available memory.` to `Add interface for publishing `top`-like information, such as uptime and available memory.`

By the way, since we are not fixing an issue we might change Fix to Closes.

2021-11-09 11:18 UTC, rbino approved these changes

2021-11-09 11:33 UTC, merged